name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.21"
          - "go: 1.22.0-rc.1"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build & Test
        run: |
          make test
